baseurl: "https://abw2022.netlify.app/"
title: "Chickpea Ascochyta Blight Workshop 2022"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "3250625849"

params:
  # Conference info
  Name: "Chickpea Ascochyta Blight Workshop 2022" # National Chickpea
  Description: "Join us at the Australian National Chickpea Ascochyta Blight Workshop 2022, October 12-14 2022, Agricultural Institute Charles Sturt University, 322 Pine Gully Rd Wagga Wagga NSW 2795"
  Date: "October 12-14 2022"
  # Price: "Only $100" # If your event is free, just comment this line
  Venue: "Agricultural Institute, Charles Sturt University"
  Address: "322 Pine Gully Rd" # , Charles Sturt University NSW 2795
  City:  "Wagga Wagga"
  State: "New South Wales"
  Images: ["/img/Twitter_card.png"]
  GoogleMapsKey:  "" # enter as environment variable for deployment

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - sponsors
    - partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "http://register.example.com"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  # ForkButton:
  #   repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Grains Research and Development Cooperation"
      logo: "/img/grdc-logo-vertical.png"
      url: "https://grdc.com.au"

  # List of Partners
  Partners:
    - name: "NSW Department of Primary Industries"
      logo: "/img/nswdpi-logo.jpg"
      url: "https://www.dpi.nsw.gov.au/"
    - name: "Agriculture Victoria"
      logo: "/img/AgriVic_logo.png"
      url: "https://agriculture.vic.gov.au/home"
    - name: "Griffith University"
      logo: "/img/griffith_logo.png"
      url: "https://www.griffith.edu.au"
    - name: "The South Australian Research and Development Institute"
      logo: "/img/sardi-vector-logo.png"
      url: "https://pir.sa.gov.au/research"
    - name: "The Commonwealth Scientific and Industrial Research Organisation"
      logo: "/img/csiro-logo.png"
      url: "https://www.csiro.au/en/research/plants/Pathogens-weeds"
    - name: "Centre for Crop and Disease Management, Curtin University"
      logo: "/img/curtin.png"
      url: "https://www.ccdm.com.au/"
    - name: "The International Center for Agriculture Research in the Dry Areas"
      logo: "/img/icarda-logo-long.png"
      url: "https://www.icarda.org/"

  # The entire schedule
  Schedule:
    - name: "TBA"
      time: "9h00-17h00"

    - name: "Dr. Ido Bar"
      photo: "/img/Ido_griffith_headshot_rect.jpg"
      bio: "Originally from Israel, I arrived to Australia in 2011 for a PhD at the University of the Sunshine Coast, developing surrogate biotechnology for the bluefin tuna industry, using advanced molecular and genomics methods. I joined Griffith University in 2016 as a postdoc, which quickly evolved to a lecturer (Biosciences) and research fellow position at the Centre for Planetary Health and Food Security. I bring comprehensive knowledge, skills and expertise in molecular biology, genomics and bioinformatics to study crop and pathogen genomics, crop-pathogen molecular interactions and to develop novel pathogen diagnostics methods. I aspire to develop applied research solutions in tight collaboration with the agriculture and aquaculture industries to overcome diseases and other production bottlenecks to help future food security."
      company: "Griffith University"
      link:
        href: "http://twitter.com/DrIdoBar"
        text: "@dridobar"
      presentation:
       title: "Avirulance Genes and Effector Molecules Repertoire of <i>Ascochyta rabiei</i>"
       description: "TBA"
       time: "10h00"

  ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
  