baseurl: "https://abw2022.netlify.app/"
title: "Chickpea Ascochyta Blight Workshop 2022"
canonifyurls: true
theme:
  - hugo-conference
# theme: "hugo-conference"

# GoogleAnalytics: "G-QPLB6PJSJE"

params:
  # Conference info
  Name: "Chickpea Ascochyta Blight Workshop 2022" # National Chickpea
  Description: "Join us at the Australian National Chickpea Ascochyta Blight Workshop 2022, October 12-14 2022, Charles Sturt University Convention Centre, 286 Pine Gully Rd Wagga Wagga NSW 2795"
  Date: "October 12-14 2022"
  # Price: "$300" # If your event is free, just comment this line
  Venue: "Charles Sturt University Convention Centre"
  Address: "286 Pine Gully Rd" # , Charles Sturt University NSW 2795
  City:  "Wagga Wagga"
  State: "New South Wales"
  Images: ["/img/Twitter_card.png"]
  GoogleMapsKey:  "" # enter as environment variable for deployment
  # Google Analytics 4
  GoogleAnalyticsID: "" # enter as environment variable for deployment
  # enter a twitter list to follow
  TwitterFeed: "https://twitter.com/DrIdoBar/lists/1557876531015208960"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - abstract
    - speakers
    - schedule
    - sponsors
    - partners
    - contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    abstract: "Abstract Submission"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "https://app.secure.griffith.edu.au/griffithpay/chickpea-ascochyta-blight-workshop-2022.html"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
#   ForkButton:
  #   repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Grains Research and Development Cooperation"
      logo: "/img/grdc-logo-vertical.png"
      url: "https://grdc.com.au"

  # List of Partners
  Partners:
    - name: "NSW Department of Primary Industries"
      logo: "/img/nswdpi-logo.jpg"
      url: "https://www.dpi.nsw.gov.au/"
    - name: "Agriculture Victoria"
      logo: "/img/AgriVic_logo.png"
      url: "https://agriculture.vic.gov.au/home"
    - name: "Griffith University"
      logo: "/img/griffith_logo.png"
      url: "https://www.griffith.edu.au"
    - name: "The South Australian Research and Development Institute"
      logo: "/img/sardi-vector-logo.png"
      url: "https://pir.sa.gov.au/research"
    - name: "The Commonwealth Scientific and Industrial Research Organisation"
      logo: "/img/csiro-logo.png"
      url: "https://www.csiro.au/en/research/plants/Pathogens-weeds"
    - name: "Centre for Crop and Disease Management, Curtin University"
      logo: "/img/curtin.png"
      url: "https://www.ccdm.com.au/"
    - name: "The International Center for Agriculture Research in the Dry Areas"
      logo: "/img/icarda-logo-long.png"
      url: "https://www.icarda.org/"

  # The entire schedule
  Schedule:
    - name: "Field Day"
      day: "Wed 12 Oct"
      time: "9:00-15:00"
      description: "Field day organised by the NSW Department of Primary Industries (DPI), to be held concurrently with participants of the National Plant Pathology meeting"
      
    - name: "Opening Address"
      day: "Thu 13 Oct"
      time: "9:00-9:10"
      description: "Opening address and house keeping"

    - name: "Industry Overview"
      day: "Thu 13 Oct"
      time: "9:10-9:25"
      description: "Overview of the Australian chickpea industry"

    - name: "Prof. Bunyamin Tar'an"
      photo: "/img/bunyamin_taran_cropped.jpg"
      bio: "Ministry of Agriculture Strategic Research Program (SRP) Chair in Chickpea and Flax Breeding and Genetics."
      company: "University of Saskatchewan"
      link:
        href: "https://agbio.usask.ca/faculty-and-staff/people-pages/bunyamin-taran.php"
        text: "Research Profile"
      presentation:
        title: "Keynote Presentation"
        description: "An Integrated Approach for Improvement of Ascochyta Blight Resistance in Chickpea"
        day: "Thu 13 Oct"
        time: "9:25-9:55"

    - name: "Keynote Q&A"
      day: "Thu 13 Oct"
      time: "9:55-10:10"
      description: "Keynote presentation questions and discussion"

    - name: "Morning Tea"
      day: "Thu 13 Oct"
      time: "10:10-10:40"
      description: "Morning tea, meet and greet, flash presentations"

    - name: "'Understanding the Host' session"
      day: "Thu 13 Oct"
      time: "10:40-12:30"
      description: "Oral persentations focusing on the host (chickpea) perspective (10 or 20 min each)"

    - name: "Lunch"
      day: "Thu 13 Oct"
      time: "12:30-13:30"
      description: "Lunch and networking, flash presentations"

    - name: "'Understanding the Pathogen' session"
      day: "Thu 13 Oct"
      time: "13:30-15:00"
      description: "Oral persentations focusing on the pathgen (*Ascochyta rabiei*) perspective (10 or 20 min each)"

    - name: "Afternoon Tea"
      day: "Thu 13 Oct"
      time: "15:00-15:20"
      description: "Afternoon tea and networking, flash presentations"

    - name: "'Disease Management' session"
      day: "Thu 13 Oct"
      time: "15:20-17:00"
      description: "Oral persentations on Disease Management (10 or 20 min each)"
      
    - name: "Social Dinner"
      day: "Thu 13 Oct"
      time: "18:30"
      description: "Dine, mingle, socialise and network at the [The Wild Vine Vineyard](https://www.thewildvine.com.au/)"
      
    - name: "'Disease Control and Diagnostics' session"
      day: "Fri 14 Oct"
      time: "9:00-9:40"
      description: "Oral persentations on Innovation and Technology for Disease Controls and Diagnostics (10 or 20 min each)"

    - name: "'Industry Updates' session"
      day: "Fri 14 Oct"
      time: "9:40-10:00"
      description: "Oral persentations from Growers' and Industry (10 or 20 min each)"

    - name: "Morning Tea"
      day: "Fri 14 Oct"
      time: "10:20-10:50"
      description: "Morning tea and netwroking, flash presentations"

    - name: "Panel Discussion"
      day: "Fri 14 Oct"
      time: "10:50-12:30"
      description: "Panel discussion and workshop summary"

    - name: "Lunch"
      day: "Fri 14 Oct"
      time: "12:30-13:30"
      description: "Lunch and farewell"


ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]