[build]
command = "hugo"
publish = "public"
[build.environment]
HUGO_VERSION = "0.92.0"

[context]
[context.branch-deploy]
command = "hugo --themesDir themes -t hugo-conference -F -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "hugo --themesDir themes -t hugo-conference -F -b $DEPLOY_PRIME_URL"
[context.production]
[context.production.environment]
HUGO_ENV = "production"
